/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Persona.
func (mg *Persona) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: mg.Spec.ForProvider.PermissionSets,
		Extract:       reference.ExternalName(),
		References:    mg.Spec.ForProvider.PermissionSetRefs,
		Selector:      mg.Spec.ForProvider.PermissionSetRefSelector,
		To: reference.To{
			List:    &PermissionSetList{},
			Managed: &PermissionSet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PermissionSets")
	}
	mg.Spec.ForProvider.PermissionSets = mrsp.ResolvedValues
	mg.Spec.ForProvider.PermissionSetRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this Team.
func (mg *Team) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.ManagedBy.User,
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ManagedBy.UserRef,
		Selector:     mg.Spec.ForProvider.ManagedBy.UserRefSelector,
		To: reference.To{
			List:    &UserList{},
			Managed: &User{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ManagedBy.User")
	}
	mg.Spec.ForProvider.ManagedBy.User = rsp.ResolvedValue
	mg.Spec.ForProvider.ManagedBy.UserRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: mg.Spec.ForProvider.Members,
		Extract:       reference.ExternalName(),
		References:    mg.Spec.ForProvider.UserRefs,
		Selector:      mg.Spec.ForProvider.UserRefSelector,
		To: reference.To{
			List:    &UserList{},
			Managed: &User{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Members")
	}
	mg.Spec.ForProvider.Members = mrsp.ResolvedValues
	mg.Spec.ForProvider.UserRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: mg.Spec.ForProvider.Personas,
		Extract:       reference.ExternalName(),
		References:    mg.Spec.ForProvider.PersonaRefs,
		Selector:      mg.Spec.ForProvider.PersonaRefSelector,
		To: reference.To{
			List:    &PersonaList{},
			Managed: &Persona{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Personas")
	}
	mg.Spec.ForProvider.Personas = mrsp.ResolvedValues
	mg.Spec.ForProvider.PersonaRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this User.
func (mg *User) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: mg.Spec.ForProvider.Personas,
		Extract:       reference.ExternalName(),
		References:    mg.Spec.ForProvider.PersonaRefs,
		Selector:      mg.Spec.ForProvider.PersonaRefSelector,
		To: reference.To{
			List:    &PersonaList{},
			Managed: &Persona{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Personas")
	}
	mg.Spec.ForProvider.Personas = mrsp.ResolvedValues
	mg.Spec.ForProvider.PersonaRefs = mrsp.ResolvedReferences

	return nil
}
